### ISSUE TITLE
400 error on each request

### ISSUE THREAD

**Issue by lchenneberg** [bunnymatic/faye-server-heroku#1]
How can I fix this issue?

2012-07-29T18:41:21+00:00 heroku[router]: GET thawing-journey-8995.herokuapp.com/faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fsubscribe%22%2C%22clientId%22%3A%2210n3jzy1ixtg9d1yyqpaj0oauori%22%2C%22subscription%22%3A%22%2Ffoo%22%2C%22id%22%3A%222%22%7D%2C%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22clientId%22%3A%2210n3jzy1ixtg9d1yyqpaj0oauori%22%2C%22connectionType%22%3A%22callback-polling%22%2C%22id%22%3A%223%22%2C%22advice%22%3A%7B%22timeout%22%3A0%7D%7D%5D&jsonp=**jsonp2** dyno=web.1 queue=0 wait=0ms service=1ms status=200 bytes=292
2012-07-29T18:41:21+00:00 app[web.1]: 2012-07-29 18:41:21 [ERROR] [Faye.NodeAdapter] Received request with no message: "curl -X GET 'http://thawing-journey-8995.herokuapp.com/faye'"
2012-07-29T18:41:21+00:00 heroku[router]: GET thawing-journey-8995.herokuapp.com/faye dyno=web.1 queue=0 wait=0ms service=4ms status=400 bytes=21

**Comment by bunnymatic** [comment]
At first glance, this looks like it should work, but clearly you are not getting subscribed (/meta/subscribe is the first call to hook up the client/server).  Did you set the mount point on the server to /faye?

if not, check this line in the server code.
var bayeux = new faye.NodeAdapter({mount:YOUR_MOUNT_PREFIX_GOES_HERE});

YOUR_MOUNT_PREFIX_GOES_HERE should be /faye (for the example you've sent).

And can you show me your client side code?  I suspect something simple like the client and server aren't quite in sync because of the mount point, or some other simple config thing.

I'll try to take a closer look tomorrow.  I might also recommend checking out the Faye documentation (faye.jcoglan.com).  They may be able to shed some light on the connection issues.

**Comment by lchenneberg** [comment]
Ok Thank you, I'll push it on a repository tonight. Is it use Websocket? Cedar on Heroku don't seem to manage them yet.

**Comment by bunnymatic** [comment]
In the app that I'm running, i've told faye not to use websockets - as
you noticed, it doesn't look like heroku is quite ready for that.
But aside from that, it's been working fine for me.

Let me know when you have a repo and i can give it a look see.

On Mon, Jul 30, 2012 at 4:53 AM, Ludovic Chenneberg
reply@reply.github.com
wrote:

> Ok Thank you, I'll push it on a repository tonight. Is it use Websocket? Cedar on Heroku don't seem to manage them yet.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bunnymatic/faye-server-heroku/issues/1#issuecomment-7366340

## 

Visit http://bunnymatic.com

**Comment by bunnymatic** [comment]
Check your Procfile.  This is the file that tells heroku how to start things up.  I just pushed a new version of that file that may solve the problem.  I'd renamed my server.js file and forgot to make that update in the Procfile.  Check that out and let me know.

On a sidenote, I was able to find this by starting it up locally using heroku and foreman gems.  If you haven't tried that, i'd recommend that as a first cut debugging step.

**Comment by lchenneberg** [comment]
As promised this is my repository, https://github.com/lchenneberg/ArubaPushService. I'm Sorry for the delay. I was really busy last week

**Comment by bunnymatic** [comment]
I was able to get your app up and running without issue and without any code changes.  I pulled, created a heroku app, and pushed and things seemed to be working.

After deploying to heroku, i 
1. hit the root url.  Saw the funk message
2. hit the faye client javascript url ( /faye/client.js ). Verified that the app was serving up it's javascript.
3. Launched my faye client app, updated the urls to point to this heroku instance and validated that it worked.

What I did notice occasional timeout messages in my server app logs, but that didn't seem to affect the system.  Could you be running into cross-domain javascript issues?  How are you talking to the server?  Have you tried the Faye client code?  If not... here's a pretty simple sinatra app which i've used for testing my own server.

https://github.com/bunnymatic/faye-client-sinatra

Let me know if this doesn't get you up and running.

Jon

**Comment by lchenneberg** [comment]
yes i'm operating trough cross domain javascript. Maybe it's linked to cors.
I tryed to comunicate with curl but 400 error return every time

I'll try the faye client sinatra and let you know. thx

**Comment by bunnymatic** [comment]
I think Faye is pretty smart about cross site stuff.  I did not do anything
special with the client/server code to handle that.  But I have seen
requests which are clearly using jsonp (with the sinatra client/server).
 Maybe your curl is just not the right format?

As I mentioned before, this stuff that I put together is a very thin
wrapper on Faye.  You may have better luck starting from there
documentation.  http://faye.jcoglan.com

Let me know if you get things rolling.

cheers
Jon
On Tue, Aug 7, 2012 at 8:47 PM, Ludovic Chenneberg <notifications@github.com

> wrote:
> 
> yes i'm operating trough cross domain javascript. Maybe it's linked to
> cors.
> I tryed to comunicate with curl but 400 error return every time
> 
> I'll try the faye client sinatra and let you know. thx
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bunnymatic/faye-server-heroku/issues/1#issuecomment-7574291.

## 

Visit http://bunnymatic.com
